[features]
seeds = false
skip-lint = false
[programs.devnet]
flappy_bird = "Du3i8JCwm2QfuieJDgkUqaAmX69fRNEqSpy4aN5297DY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/sangeet/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

