[features]
seeds = false
skip-lint = false
[programs.localnet]
flappy_bird = "37ZT5GsJGt2hNHL5i2Txnijz3DfXKHYG34yVxc57uzKR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/shubh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
